name: CI/CD Pipeline for dev environment
on:
  push:
    branches:
      - dev

jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:  
      - name: first
        run: echo "This is the first workflow"